interface Window {
  test: any;
  Event: any;
  CustomEvent: any;
  _trackerFlag: { [propName: string]: any };
  _trackerPageId: string;
  _trackerAnalyseDisableDide: boolean;
  _TrackerGlobalData: any;
}

interface HTMLElement {
  _trackerInfo: any;
  _isWatchTrack: boolean;
}

interface Element {
  content: string;
}

declare const _TrackerGlobalData: { pageCode?: string; oldPageCode?: string; _trackerFlag: Object };
/** Declaration file generated by dts-gen */
